### ISSUE TITLE
Callback was already called in async.js

### ISSUE THREAD

**Issue by tanimakar** [suguru03/neo-async#58] opened 2018-08-01 07:34 UTC
While doing npm start I am getting the error in node_modules\neo-async\async.js:14:11

 **throw new Error('Callback was already called.');**

Also this:
**12% building modules 19/19 modules 0 active× ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency**

My package.json:

{
  "name": "sample-app-angular-hybrid",
  "description": "Architecture overview demo for Angular UI-Router",
  "version": "1.0.2",
  "scripts": {
    "clean": "shx rm -rf _bundles transpiled",
    "start": "npm run serve",
    "serve": "webpack-dev-server --open --progress",
    "build": "npm run clean && webpack --mode=production --progress",
    "test": "npm run build && cypress-runner run --path .",
    "test:open": "npm run build && cypress-runner open --path .",
    "gh-pages": "git checkout gh-pages && git rebase master && rm -rf node_modules && yarn install && webpack && git add -f _bundles && git commit -m 'publish gh-pages' && git push origin gh-pages:gh-pages --force && git checkout master"
  },
  "contributors": [
    {
      "name": "Chris Thielen",
      "web": "https://github.com/christopherthielen"
    }
  ],
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/ui-router/sample-app-angular-hybrid.git"
  },
  "dependencies": {
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/router": "^6.1.0",
    "@angular/upgrade": "^6.0.9",
    "@uirouter/angular-hybrid": "^6.0.1",
    "@uirouter/visualizer": "^6.0.2",
    "angular": "^1.7.2",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "webpack": "^4.16.3",
    "webpack-dev-server": "^3.1.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^6.1.1",
    "@ngtools/webpack": "^6.1.1",
    "@types/angular": "^1.6.49",
    "@uirouter/cypress-runner": "^1.0.9",
    "shx": "^0.3.2",
    "source-map-loader": "^0.2.3",
    "typescript": ">=2.7.2 <2.8.0",
    "webpack-cli": "^3.1.0"
  }
}

**Comment by suguru03** [comment] 2018-08-01 18:09
@tanimakar 
Thank you for the issue! 🙂 

It seems not to be a neo-async issue.

Are you using this repository? 
https://github.com/ui-router/sample-app-angular-hybrid

I tried it but I can't reproduce it. How can I reproduce it?

**Comment by tanimakar** [comment] 2018-08-02 07:46
yes I am using this https://github.com/ui-router/sample-app-angular-hybrid 
And I wanted to have a hybrid application having both AngularJs and Ang6

**Comment by suguru03** [comment] 2018-08-13 17:31
It is not a neo-async issue, I'm going to close it.

**Closed by suguru03** 2018-08-13 17:31 UTC
